### ISSUE TITLE
Announced resources

### ISSUE THREAD

**Issue by paulvitic** [actility/ong#1]
Hi,
As far as I can see, resource annoucement procedures are not implemented. Is this correct? 
If so how would you advise to implement this capabilitiy?
Thanks.

**Comment by jbreich** [comment]
Hello,

You are right announced resources are not implemented
The SCL behavior is implemented in the java maven project under gscl/scl.app.me. You will find the behavior of each ETSI M2M resources in src/main/java/com/actility/m2m/scl/res/. So first you will need to implement Annc resources for the resources that you target (for example ApplicationAnnc, ContainerAnnc etc...). Then implement the announcement of resources in there original resources (respectively Application, Container etc...). Depending on your requirements you will maybe need to implement a client state machine in non Annc resources for example to implement a retry mechanism. You can look at the Subcription resource which creates a client state machine in SubscriptionManager to send notifications to contactURI.

Regards

**Comment by paulvitic** [comment]
OK thanks I will be working on this.

**Comment by jbreich** [comment]
OK thank you for your help
I you have any question feel free to ask

**Comment by paulvitic** [comment]
Hello Jean-Baptiste,

I would like to ask you some questions about this project. Could you pls contact me at my email.
